-- create table employee (id bigint generated by default as identity (start with 1), emp_name varchar(255), cv clob, primary key (id));
create table employee (id bigint generated by default as identity (start with 1), emp_name varchar(255), cv varchar(4000), primary key (id));
create table phone (id bigint generated by default as identity (start with 1), phone_type varchar(20), phone_number varchar(20), employee_id bigint, primary key (id));

insert into employee (id, emp_name, cv) values (1, 'John Doe', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
insert into employee (id, emp_name, cv) values (2, 'Jane Poe', 'Vestibulum vulputate vulputate lobortis.');
insert into phone (id, phone_type, phone_number, employee_id) values (1, 'home', '111111', 1);
insert into phone (id, phone_type, phone_number, employee_id) values (2, 'office', '222222', 1);
insert into phone (id, phone_type, phone_number, employee_id) values (3, 'home', '333333', 2);
insert into phone (id, phone_type, phone_number, employee_id) values (4, 'office', '444444', 2);