-- create table employee (id bigint generated by default as identity (start with 1), emp_name varchar(255), cv clob, primary key (id));
create table employee (id bigint generated by default as identity (start with 1), emp_name varchar(255), cv varchar(4000), primary key (id));
create table phone (id bigint generated by default as identity (start with 1), phone_type varchar(20), phone_number varchar(20), employee_id bigint, primary key (id));
